//
//  TestFeature1Presenter.swift
//  gitFlowTestApp
//
//  Created by Miljana Ratkov on 24/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TestFeature1PresentationLogic
{
  func presentSomething(response: TestFeature1.Something.Response)
}

class TestFeature1Presenter: TestFeature1PresentationLogic
{
  weak var viewController: TestFeature1DisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TestFeature1.Something.Response)
  {
    let viewModel = TestFeature1.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
