//
//  TestFeature1Worker.swift
//  gitFlowTestApp
//
//  Created by Miljana Ratkov on 24/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TestFeature1Worker
{
  func doSomeWork()
  {
  }
}
