//
//  TestFeature1Router.swift
//  gitFlowTestApp
//
//  Created by Miljana Ratkov on 24/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TestFeature1RoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol TestFeature1DataPassing
{
  var dataStore: TestFeature1DataStore? { get }
}

class TestFeature1Router: NSObject, TestFeature1RoutingLogic, TestFeature1DataPassing
{
  weak var viewController: TestFeature1ViewController?
  var dataStore: TestFeature1DataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: TestFeature1ViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: TestFeature1DataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
