//
//  TestFeature1Interactor.swift
//  gitFlowTestApp
//
//  Created by Miljana Ratkov on 24/12/2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TestFeature1BusinessLogic
{
  func doSomething(request: TestFeature1.Something.Request)
}

protocol TestFeature1DataStore
{
  //var name: String { get set }
}

class TestFeature1Interactor: TestFeature1BusinessLogic, TestFeature1DataStore
{
  var presenter: TestFeature1PresentationLogic?
  var worker: TestFeature1Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TestFeature1.Something.Request)
  {
    worker = TestFeature1Worker()
    worker?.doSomeWork()
    
    let response = TestFeature1.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
